package xyz.zyrex.bedrockantidupe;

import net.milkbowl.vault.economy.Economy;
import org.bukkit.Bukkit;
import org.bukkit.OfflinePlayer;
import org.bukkit.entity.Player;

import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Rolls back money generated by a confirmed duplicated-item sale.
 *
 * This class only performs a rollback when it receives a recorded
 * EconomyTransaction. It does not guess how much money should be removed.
 */
public final class EconomyRollbackManager {

    private final BedrockAntiDupe plugin;
    private final DiscordAlertManager discord;

    private final Map<UUID, Long> rolledBackTransactions =
            new ConcurrentHashMap<>();

    public EconomyRollbackManager(
            BedrockAntiDupe plugin,
            DiscordAlertManager discord
    ) {
        this.plugin = plugin;
        this.discord = discord;
    }

    /**
     * Rolls back the exact recorded value of a sale.
     */
    public RollbackResult rollback(
            EconomyTransaction transaction
    ) {
        if (!plugin.getConfig().getBoolean("economy.enabled", true)
                || !plugin.getConfig().getBoolean("economy.vault", true)) {
            return RollbackResult.failed(UUID.randomUUID(), 0, 0, "Economy rollback is disabled.");
        }

        if (transaction == null) {
            return RollbackResult.failed(
                    UUID.randomUUID(),
                    0,
                    0,
                    "Transaction is null."
            );
        }

        UUID transactionId = transaction.transactionId();

        if (!transaction.rollbackEligible()) {
            return RollbackResult.failed(
                    transactionId,
                    transaction.exactValue(),
                    0,
                    "Transaction is not eligible for rollback."
            );
        }

        /*
         * Never process the same transaction twice.
         */
        if (rolledBackTransactions.putIfAbsent(
                transactionId,
                System.currentTimeMillis()
        ) != null) {
            return RollbackResult.failed(
                    transactionId,
                    transaction.exactValue(),
                    0,
                    "Transaction was already processed."
            );
        }

        Economy economy = resolveEconomy();
        if (economy == null) {
            rolledBackTransactions.remove(transactionId);
            return RollbackResult.failed(
                    transactionId, transaction.exactValue(), 0,
                    "Vault economy provider is unavailable."
            );
        }

        UUID playerId = transaction.playerId();

        /*
         * Vault 1.7.1 exposes OfflinePlayer/String based economy methods,
         * not UUID based methods.
         */
        OfflinePlayer offlinePlayer =
                Bukkit.getOfflinePlayer(playerId);

        Player onlinePlayer =
                Bukkit.getPlayer(playerId);

        double balance =
                economy.getBalance(offlinePlayer);

        double requested = Math.max(0.0, transaction.exactValue());
        double maxRollback = plugin.getConfig().getDouble("economy.max-single-rollback", 0.0);
        if (maxRollback > 0.0) requested = Math.min(requested, maxRollback);

        double withdraw =
                Math.min(
                        balance,
                        requested
                );

        if (withdraw <= 0.0) {
            rolledBackTransactions.remove(transactionId);

            return RollbackResult.failed(
                    transactionId,
                    requested,
                    0,
                    "Player has no available balance to rollback."
            );
        }

        var response =
                economy.withdrawPlayer(
                        offlinePlayer,
                        withdraw
                );

        if (!response.transactionSuccess()) {
            rolledBackTransactions.remove(transactionId);

            return RollbackResult.failed(
                    transactionId,
                    requested,
                    0,
                    "Economy provider rejected the withdrawal."
            );
        }

        RollbackResult result;

        if (withdraw >= requested) {
            result =
                    RollbackResult.success(
                            transactionId,
                            requested,
                            withdraw
                    );
        } else {
            result =
                    RollbackResult.partial(
                            transactionId,
                            requested,
                            withdraw,
                            "Only the player's available balance could be rolled back."
                    );
        }

        sendNotification(
                transaction,
                result,
                onlinePlayer
        );

        return result;
    }

    /**
     * Rolls back a sale only when the caller has already confirmed
     * that the sold item originated from a duplication.
     */
    public RollbackResult rollbackConfirmedDupeSale(
            EconomyTransaction transaction
    ) {
        if (transaction == null) {
            return RollbackResult.failed(
                    UUID.randomUUID(),
                    0,
                    0,
                    "Transaction is null."
            );
        }

        if (!transaction.generatedMoney()) {
            return RollbackResult.failed(
                    transaction.transactionId(),
                    transaction.exactValue(),
                    0,
                    "Transaction did not generate money."
            );
        }

        return rollback(transaction);
    }

    /**
     * Reads the player's economy balance when Vault and an economy provider
     * are actually available. Returns null when the optional integration is
     * unavailable, allowing core anti-dupe protection to operate normally.
     *
     * This method is intentionally kept behind the economy integration
     * boundary so event listener classes do not have a hard Vault linkage.
     */
    public Double getBalance(Player player) {
        if (player == null
                || !plugin.getConfig().getBoolean("economy.enabled", true)
                || !plugin.getConfig().getBoolean("economy.vault", true)) {
            return null;
        }

        Economy economy = resolveEconomy();
        if (economy == null) return null;

        try {
            double balance = economy.getBalance(player);
            return Double.isFinite(balance) && balance >= 0.0D ? balance : null;
        } catch (RuntimeException ex) {
            plugin.getLogger().warning("[AntiDupe] Failed to read economy balance: " + ex.getMessage());
            return null;
        }
    }

    /**
     * Gets the Vault economy provider.
     */
    private Economy resolveEconomy() {
        if (Bukkit.getPluginManager()
                .getPlugin("Vault") == null) {

            plugin.getLogger().warning(
                    "Vault is not installed. "
                            + "Economy rollback is disabled."
            );

            return null;
        }

        var registration =
                Bukkit.getServicesManager()
                        .getRegistration(
                                Economy.class
                        );

        if (registration == null) {
            plugin.getLogger().warning(
                    "No Vault economy provider found."
            );

            return null;
        }

        return registration.getProvider();
    }

    private void sendNotification(
            EconomyTransaction transaction,
            RollbackResult result,
            Player player
    ) {
        if (discord == null) {
            return;
        }

        String playerName =
                player != null
                        ? player.getName()
                        : transaction.playerId().toString();

        discord.sendEconomyRollbackAlert(
                playerName,
                transaction.playerId().toString(),
                transaction.exactValue(),
                result.rolledBackAmount(),
                result.status().name()
                        + ": "
                        + result.message(),
                transaction.transactionId().toString()
        );
    }

    /**
     * Removes old rollback records from memory.
     */
    public void cleanup(long maxAgeMillis) {
        long now = System.currentTimeMillis();

        rolledBackTransactions
                .entrySet()
                .removeIf(
                        entry ->
                                now - entry.getValue()
                                        > maxAgeMillis
                );
    }

    /**
     * Clears rollback state.
     */
    public void clear() {
        rolledBackTransactions.clear();
    }

    /**
     * Returns whether Vault economy is available.
     */
    public boolean isAvailable() {
        return plugin.getConfig().getBoolean("economy.enabled", true)
                && plugin.getConfig().getBoolean("economy.vault", true)
                && resolveEconomy() != null;
    }
    }
