package xyz.zyrex.bedrockantidupe;

import org.bukkit.Bukkit;
import org.bukkit.OfflinePlayer;
import org.bukkit.entity.Player;

import java.lang.reflect.Method;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Rolls back money generated by a confirmed duplicated-item sale.
 *
 * Vault is deliberately accessed through reflection so the core plugin has
 * zero runtime linkage to Vault classes when Vault is not installed.
 */
public final class EconomyRollbackManager {

    private final BedrockAntiDupe plugin;
    private final DiscordAlertManager discord;
    private final Map<UUID, Long> rolledBackTransactions = new ConcurrentHashMap<>();

    private volatile Class<?> economyClass;
    private volatile Object economyProvider;

    public EconomyRollbackManager(BedrockAntiDupe plugin, DiscordAlertManager discord) {
        this.plugin = plugin;
        this.discord = discord;
    }

    public RollbackResult rollback(EconomyTransaction transaction) {
        if (!economyEnabled()) {
            return RollbackResult.failed(UUID.randomUUID(), 0, 0,
                    "Economy rollback is disabled.");
        }
        if (transaction == null) {
            return RollbackResult.failed(UUID.randomUUID(), 0, 0, "Transaction is null.");
        }

        UUID transactionId = transaction.transactionId();
        if (!transaction.rollbackEligible()) {
            return RollbackResult.failed(transactionId, transaction.exactValue(), 0,
                    "Transaction is not eligible for rollback.");
        }

        if (rolledBackTransactions.putIfAbsent(transactionId, System.currentTimeMillis()) != null) {
            return RollbackResult.failed(transactionId, transaction.exactValue(), 0,
                    "Transaction was already processed.");
        }

        Object economy = resolveEconomy();
        if (economy == null) {
            rolledBackTransactions.remove(transactionId);
            return RollbackResult.failed(transactionId, transaction.exactValue(), 0,
                    "Vault economy provider is unavailable.");
        }

        UUID playerId = transaction.playerId();
        OfflinePlayer offlinePlayer = Bukkit.getOfflinePlayer(playerId);
        Player onlinePlayer = Bukkit.getPlayer(playerId);

        try {
            double balance = invokeDouble(economy, "getBalance",
                    new Class<?>[]{OfflinePlayer.class}, offlinePlayer);

            if (!Double.isFinite(balance) || balance < 0.0D) {
                rolledBackTransactions.remove(transactionId);
                return RollbackResult.failed(transactionId, transaction.exactValue(), 0,
                        "Economy provider returned an invalid balance.");
            }

            double requested = Math.max(0.0D, transaction.exactValue());
            double maxRollback = plugin.getConfig().getDouble("economy.max-single-rollback", 0.0D);
            if (maxRollback > 0.0D) {
                requested = Math.min(requested, maxRollback);
            }

            double withdraw = Math.min(balance, requested);
            if (withdraw <= 0.0D) {
                rolledBackTransactions.remove(transactionId);
                return RollbackResult.failed(transactionId, requested, 0,
                        "Player has no available balance to rollback.");
            }

            Object response = invoke(economy, "withdrawPlayer",
                    new Class<?>[]{OfflinePlayer.class, double.class},
                    offlinePlayer, withdraw);

            boolean success = response != null &&
                    Boolean.TRUE.equals(invoke(response, "transactionSuccess", new Class<?>[0]));

            if (!success) {
                rolledBackTransactions.remove(transactionId);
                return RollbackResult.failed(transactionId, requested, 0,
                        "Economy provider rejected the withdrawal.");
            }

            RollbackResult result = withdraw >= requested
                    ? RollbackResult.success(transactionId, requested, withdraw)
                    : RollbackResult.partial(transactionId, requested, withdraw,
                            "Only the player's available balance could be rolled back.");

            sendNotification(transaction, result, onlinePlayer);
            return result;
        } catch (ReflectiveOperationException | RuntimeException ex) {
            rolledBackTransactions.remove(transactionId);
            plugin.getLogger().warning("[AntiDupe] Economy operation failed safely: "
                    + ex.getClass().getSimpleName() + ": " + ex.getMessage());
            return RollbackResult.failed(transactionId, transaction.exactValue(), 0,
                    "Economy provider operation failed.");
        }
    }

    public RollbackResult rollbackConfirmedDupeSale(EconomyTransaction transaction) {
        if (transaction == null) {
            return RollbackResult.failed(UUID.randomUUID(), 0, 0, "Transaction is null.");
        }
        if (!transaction.generatedMoney()) {
            return RollbackResult.failed(transaction.transactionId(), transaction.exactValue(), 0,
                    "Transaction did not generate money.");
        }
        return rollback(transaction);
    }

    public Double getBalance(Player player) {
        if (player == null || !economyEnabled()) {
            return null;
        }

        Object economy = resolveEconomy();
        if (economy == null) return null;

        try {
            double balance = invokeDouble(economy, "getBalance",
                    new Class<?>[]{OfflinePlayer.class}, player);
            return Double.isFinite(balance) && balance >= 0.0D ? balance : null;
        } catch (ReflectiveOperationException | RuntimeException ex) {
            plugin.getLogger().warning("[AntiDupe] Failed to read economy balance safely: "
                    + ex.getMessage());
            return null;
        }
    }

    private boolean economyEnabled() {
        return plugin.getConfig().getBoolean("economy.enabled", true)
                && plugin.getConfig().getBoolean("economy.vault", true);
    }

    /**
     * Resolve Vault only when Vault and an Economy service are actually present.
     * No Vault class is loaded when the integration is absent.
     */
    private Object resolveEconomy() {
        if (!economyEnabled()) return null;

        try {
            if (Bukkit.getPluginManager().getPlugin("Vault") == null) {
                return null;
            }

            Class<?> clazz = Class.forName("net.milkbowl.vault.economy.Economy", false,
                    getClass().getClassLoader());

            if (economyClass == clazz && economyProvider != null) {
                return economyProvider;
            }

            Object registration = Bukkit.getServicesManager()
                    .getRegistration(clazz);
            if (registration == null) return null;

            Method getProvider = registration.getClass().getMethod("getProvider");
            Object provider = getProvider.invoke(registration);
            if (provider == null) return null;

            economyClass = clazz;
            economyProvider = provider;
            return provider;
        } catch (ClassNotFoundException ex) {
            return null;
        } catch (ReflectiveOperationException | RuntimeException ex) {
            plugin.getLogger().warning("[AntiDupe] Vault resolution failed safely: "
                    + ex.getMessage());
            return null;
        }
    }

    private static Object invoke(Object target, String method, Class<?>[] types, Object... args)
            throws ReflectiveOperationException {
        Method m = target.getClass().getMethod(method, types);
        return m.invoke(target, args);
    }

    private static double invokeDouble(Object target, String method, Class<?>[] types, Object... args)
            throws ReflectiveOperationException {
        Object value = invoke(target, method, types, args);
        if (!(value instanceof Number number)) {
            throw new IllegalStateException("Economy provider returned a non-number value.");
        }
        return number.doubleValue();
    }

    private void sendNotification(EconomyTransaction transaction, RollbackResult result, Player player) {
        if (discord == null) return;

        String playerName = player != null ? player.getName() : transaction.playerId().toString();
        discord.sendEconomyRollbackAlert(
                playerName,
                transaction.playerId().toString(),
                transaction.exactValue(),
                result.rolledBackAmount(),
                result.status().name() + ": " + result.message(),
                transaction.transactionId().toString()
        );
    }

    public void cleanup(long maxAgeMillis) {
        long now = System.currentTimeMillis();
        rolledBackTransactions.entrySet().removeIf(
                entry -> now - entry.getValue() > maxAgeMillis);
    }

    public void clear() {
        rolledBackTransactions.clear();
        economyClass = null;
        economyProvider = null;
    }

    public boolean isAvailable() {
        return economyEnabled() && resolveEconomy() != null;
    }
}
