package xyz.zyrex.bedrockantidupe;

import net.milkbowl.vault.economy.Economy;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;

import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Rolls back money generated by a confirmed duplicated-item sale.
 *
 * IMPORTANT:
 * This class only performs a rollback when it receives a recorded
 * EconomyTransaction. It does not guess how much money should be
 * removed.
 */
public final class EconomyRollbackManager {

    private final BedrockAntiDupe plugin;
    private final DiscordAlertManager discord;

    private final Economy economy;

    private final Map<UUID, Long> rolledBackTransactions =
            new ConcurrentHashMap<>();

    public EconomyRollbackManager(
            BedrockAntiDupe plugin,
            DiscordAlertManager discord
    ) {

        this.plugin = plugin;
        this.discord = discord;

        this.economy =
                resolveEconomy();
    }

    /**
     * Rolls back the exact recorded value of a sale.
     */
    public RollbackResult rollback(
            EconomyTransaction transaction
    ) {

        if (transaction == null) {

            return RollbackResult.failed(
                    UUID.randomUUID(),
                    0,
                    0,
                    "Transaction is null."
            );
        }

        UUID transactionId =
                transaction.transactionId();

        /*
         * Only transactions that actually generated money
         * are eligible.
         */
        if (!transaction.rollbackEligible()) {

            return RollbackResult.failed(
                    transactionId,
                    transaction.exactValue(),
                    0,
                    "Transaction is not eligible for rollback."
            );
        }

        /*
         * Never process the same transaction twice.
         */
        if (rolledBackTransactions.putIfAbsent(
                transactionId,
                System.currentTimeMillis()
        ) != null) {

            return RollbackResult.failed(
                    transactionId,
                    transaction.exactValue(),
                    0,
                    "Transaction was already processed."
            );
        }

        if (economy == null) {

            rolledBackTransactions.remove(
                    transactionId
            );

            return RollbackResult.failed(
                    transactionId,
                    transaction.exactValue(),
                    0,
                    "Vault economy provider is unavailable."
            );
        }

        Player player =
                Bukkit.getPlayer(
                        transaction.playerId()
                );

        /*
         * Offline players can still be handled by Vault if the
         * economy implementation supports UUID-based accounts.
         */
        double balance =
                economy.getBalance(
                        transaction.playerId()
                );

        double requested =
                transaction.exactValue();

        double withdraw =
                Math.min(
                        Math.max(
                                0.0,
                                balance
                        ),
                        requested
                );

        if (withdraw <= 0.0) {

            return RollbackResult.failed(
                    transactionId,
                    requested,
                    0,
                    "Player has no available balance to rollback."
            );
        }

        var response =
                economy.withdrawPlayer(
                        transaction.playerId(),
                        withdraw
                );

        if (!response.transactionSuccess()) {

            rolledBackTransactions.remove(
                    transactionId
            );

            return RollbackResult.failed(
                    transactionId,
                    requested,
                    0,
                    "Economy provider rejected the withdrawal."
            );
        }

        RollbackResult result;

        if (withdraw >= requested) {

            result =
                    RollbackResult.success(
                            transactionId,
                            requested,
                            withdraw
                    );

        } else {

            result =
                    RollbackResult.partial(
                            transactionId,
                            requested,
                            withdraw,
                            "Only the player's available balance could be rolled back."
                    );
        }

        sendNotification(
                transaction,
                result,
                player
        );

        return result;
    }

    /**
     * Rolls back a sale only when the caller has already confirmed
     * that the sold item originated from a duplication.
     */
    public RollbackResult rollbackConfirmedDupeSale(
            EconomyTransaction transaction
    ) {

        if (transaction == null) {

            return RollbackResult.failed(
                    UUID.randomUUID(),
                    0,
                    0,
                    "Transaction is null."
            );
        }

        if (!transaction.generatedMoney()) {

            return RollbackResult.failed(
                    transaction.transactionId(),
                    transaction.exactValue(),
                    0,
                    "Transaction did not generate money."
            );
        }

        return rollback(
                transaction
        );
    }

    /**
     * Gets the Vault economy provider.
     */
    private Economy resolveEconomy() {

        if (Bukkit.getPluginManager()
                .getPlugin("Vault") == null) {

            plugin.getLogger().warning(
                    "Vault is not installed. "
                            + "Economy rollback is disabled."
            );

            return null;
        }

        var registration =
                Bukkit.getServicesManager()
                        .getRegistration(
                                Economy.class
                        );

        if (registration == null) {

            plugin.getLogger().warning(
                    "No Vault economy provider found."
            );

            return null;
        }

        return registration.getProvider();
    }

    private void sendNotification(
            EconomyTransaction transaction,
            RollbackResult result,
            Player player
    ) {

        if (discord == null) {
            return;
        }

        String playerName =
                player != null
                        ? player.getName()
                        : transaction.playerId()
                                .toString();

        discord.sendEconomyRollbackAlert(
                playerName,
                transaction.playerId()
                        .toString(),
                transaction.exactValue(),
                result.rolledBackAmount(),
                result.status().name()
                        + ": "
                        + result.message(),
                transaction.transactionId()
                        .toString()
        );
    }

    /**
     * Removes old rollback records from memory.
     */
    public void cleanup(
            long maxAgeMillis
    ) {

        long now =
                System.currentTimeMillis();

        rolledBackTransactions
                .entrySet()
                .removeIf(
                        entry ->
                                now - entry.getValue()
                                        > maxAgeMillis
                );
    }

    /**
     * Clears rollback state.
     */
    public void clear() {

        rolledBackTransactions.clear();
    }

    /**
     * Returns whether Vault economy is available.
     */
    public boolean isAvailable() {

        return economy != null;
    }
                }
