name: BedrockAntiDupe
version: 2.0.0
main: xyz.zyrex.bedrockantidupe.BedrockAntiDupe
api-version: '1.21'

authors:
  - KingBrezzX

description: >
  Advanced transaction-based anti-duplication protection
  with inventory, shulker, shop and economy rollback detection.

website: https://github.com/KingBrezzX/Anti-Duper

softdepend:
  - Vault
  - Floodgate
  - Geyser-Spigot

commands:
  antidupe:
    description: BedrockAntiDupe administration command
    usage: /antidupe <reload|status|scan|cleanup>
    aliases:
      - bad
      - bedrockantidupe

permissions:
  bedrockantidupe.admin:
    description: Access to BedrockAntiDupe administration commands
    default: op
