name: BedrockAntiDupe
version: 1.0.0
main: xyz.zyrex.bedrockantidupe.BedrockAntiDupe
api-version: '26.2'

description: Advanced event-driven anti-duplication protection for Paper servers.
author: ZyrexSMP

softdepend:
  - floodgate
  - Geyser-Spigot
  - Vault
  - PlaceholderAPI

commands:
  antidupe:
    description: BedrockAntiDupe administration command
    usage: /antidupe <reload|status|check|violations>
    aliases:
      - badupe
      - dupeguard

permissions:

  bedrockantidupe.admin:
    description: Allows administration of BedrockAntiDupe
    default: op

  bedrockantidupe.alert:
    description: Receive BedrockAntiDupe staff alerts
    default: op
